### ISSUE TITLE
Mount X11-unix and $DISPLAY env

### ISSUE THREAD

**Issue by jagedn** [yohanakh/webexondocker#2]
I needed to mount the X11-unix and set the $DISPLAY when I run the docker:

`docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -d -p 2222:22 -v /run/user/$UID/pulse/native:/tmp/webexpulsesocket --name webex webexondocker1404
`
see http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/ for more information

p.d.
thank you so much for your image. It saved my day

**Comment by yohanakh** [comment]
I am glad it helped :)

What error are you having when you don't specify the DISPLAY env var ?
On my machine I didn't need "-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix"

**Comment by jagedn** [comment]
I have a Linux Mint 18.1 and without these settings, Firefox crashed because it couldn't find a X11 server

**Comment by bettsmatt** [comment]
I needed to follow the instructions [here](http://ask.xmodulo.com/fix-broken-x11-forwarding-ssh.html) to get things working.

```
ssh root@localhost -p 2222
sudo vi /etc/ssh/sshd_config  # Add "X11UseLocalhost no"
sudo /etc/init.d/ssh restart 
docker restart <CONTAINER_ID>
ssh root@localhost -p 2222 -X startfirefox
```

This allowed me to join meetings, but not host them.

**Comment by yohanakh** [comment]
@bettsmatt What Linux do you have ? Have you tried jaden's solution ?

@jagedn , @bettsmatt - It is possible that I have some packages installed on my computer. I will try to run the instructions on clean Linux (Ubuntu) and see if something is missing.

**Comment by jagedn** [comment]
As @bettsmatt I needed to change "X11UseLocalhost no" but I thought it was not necessary

@bettsmatt I don't know much about Webex but maybe if you can't host a meeting it's because your account ?

**Comment by yohanakh** [comment]
Hi,

Somehow it stopped working for me too.  Adding the "X11UseLocalhost no" to sshd_config fixed the problem.
I have added it to the Dockerfile. If you wish to use it you need to rebuild the docker image (using `docker build -t webexondocker1404 .` command)

Thank you
